### ISSUE TITLE
Logging in as a new Google user errors out

### ISSUE THREAD

**Issue by alexanderolvera** [rpp-boc-spectre/BlueOcean#22]
Sarah noticed this issue yesterday.

When trying to login for the first time using Google OAuth, it responds with an error. 

I briefly looked into this and it seems it may be completing the authentication but failing to show the user the username form. 

the expected behavior should always halt login if the user has no username, then show the form.

**Comment by alexanderolvera** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [First time Google Sign in fails](https://trello.com/c/0SAdZzTS/43-first-time-google-sign-in-fails)

**Comment by LoganMichalicek** [comment]
Will be resolved with https://github.com/rpp-boc-spectre/BlueOcean/pull/23
